### ISSUE TITLE
recipe quite outdated

### ISSUE THREAD

**Issue by mbhall88** [conda-forge/rust-script-feedstock#15]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

rust-script is now at v0.35.0 but this package is still on v0.22.0. This has caused an issue on snakemake https://github.com/snakemake/snakemake/issues/3183 as the test suite there relies on `rust-script>=0.15.0`. There are some changes to the rust-script program since v0.22.0 that break the current usage in snakemake so we need to update it so we can test against the latest version.

What are the barriers to getting this updated? I am happy to be added as a maintainer for this repo and work on a fix @tedil. I know @dlaehnemann has also previously worked to try and get a PR merged due to some CI problems.

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by tedil** [comment]
Hi @mbhall88! You're very much welcome to help with this :) Added you as a maintainer (I think)
